//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groepsproject_Blokken
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameLogVS
    {
        public int GameID { get; set; }
        public string Player1Name { get; set; }
        public int Player1Score { get; set; }
        public string Player2Name { get; set; }
        public int Player2Score { get; set; }
        public string Winner { get; set; }
        public System.DateTime Date { get; set; }
    }
}
