//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groepsproject_Blokken
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameLogSP
    {
        public int ScoreID { get; set; }
        public int GameNumber { get; set; }
        public string PlayerName { get; set; }
        public int Score { get; set; }
        public System.DateTime Date { get; set; }
    }
}
