//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groepsproject_Blokken
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int SpelerID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<int> SPHighscore { get; set; }
        public Nullable<int> SPGamesPlayed { get; set; }
        public Nullable<int> SPGamesWon { get; set; }
        public Nullable<int> VSHighscore { get; set; }
        public Nullable<int> VSGamesPlayed { get; set; }
        public Nullable<int> VSGamesWon { get; set; }
    }
}
